const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://127.0.0.1:3100';

// Note: In a production app, the API Key would be managed via Auth context.
// For this demo, we use the one generated by our setup scripts or a default one.
const DEFAULT_API_KEY = 'ak_live_vzZpmZRBP57o1dA9mV48xHNgWrZchrcgqJiQwJ0C';

export async function apiRequest(method: string, path: string, body?: unknown) {
  try {
    const headers: Record<string, string> = {
      'Authorization': `Bearer ${DEFAULT_API_KEY}`
    };
    if (body) headers['Content-Type'] = 'application/json';

    const res = await fetch(`${API_BASE}${path}`, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });

    if (!res.ok) {
      throw new Error(`API Error: ${res.status}`);
    }

    return await res.json();
  } catch (error) {
    console.error(`[API ERROR] Failed to fetch ${path}. Ensure the backend is running at ${API_BASE}.`, error);
    return null;
  }
}
